import React, {createContext, useContext, useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter, Link, NavLink, Navigate, Route, Routes, useNavigate, useParams, useSearchParams} from 'react-router-dom';
import axios from 'axios';
import './styles.css';

const api=axios.create({baseURL:import.meta.env.VITE_API_URL||'http://127.0.0.1:5000',timeout:15000,headers:{'Content-Type':'application/json'}});
api.interceptors.request.use(c=>{const t=localStorage.getItem('nexora-token');if(t)c.headers.Authorization=`Bearer ${t}`;return c});
const messageFor=e=>{const s=e?.response?.status;if(s===401)return 'Your session has expired. Please sign in again.';if(s===403)return "You don't have permission to access this page.";if(s===404)return 'This story could not be found.';if(s===409)return 'That item already exists.';if(s===429)return 'Too many requests. Try again shortly.';if(s>=500)return 'Something went wrong. Please try again.';return e?.request?'Unable to connect. Check your connection and retry.':'Please check your details and try again.'};
const Auth=createContext(); const useAuth=()=>useContext(Auth);
const decode=t=>{try{return JSON.parse(atob(t.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')))}catch{return {}}};
function AuthProvider({children}){const [token,setToken]=useState(localStorage.getItem('nexora-token'));const [profile,setProfile]=useState(null);const user=useMemo(()=>token?decode(token):null,[token]);useEffect(()=>{if(!token){setProfile(null);return} api.get('/profile').then(r=>setProfile(r.data.user)).catch(()=>{localStorage.removeItem('nexora-token');setToken(null)})},[token]);const login=t=>{localStorage.setItem('nexora-token',t);setToken(t)};const logout=()=>{localStorage.removeItem('nexora-token');setToken(null)};return <Auth.Provider value={{token,user,profile,login,logout}}>{children}</Auth.Provider>}
const fmt=t=>{if(!t)return 'Recently updated'; const d=new Date(t);return Number.isNaN(d)?'Recently updated':d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:d.getFullYear()!==new Date().getFullYear()?'numeric':undefined})};
const text=s=>(s||'').replace(/<[^>]*>/g,'').trim(); const excerpt=s=>{let v=text(s);return v.length>170?v.slice(0,167)+'…':v};
function Toast({notice}){return notice?<div className="toast" role="status">{notice}</div>:null}
function useFetch(fn,deps=[]){const [state,set]=useState({loading:true,data:null,error:''});const load=async()=>{set(x=>({...x,loading:true,error:''}));try{set({loading:false,data:await fn(),error:''})}catch(e){set({loading:false,data:null,error:messageFor(e)})}};useEffect(()=>{load()},deps);return {...state,reload:load}}
function Shell({children}){const {token,profile,logout}=useAuth();const nav=useNavigate();const [dark,setDark]=useState(localStorage.getItem('nexora-theme')==='dark');useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);const toggle=()=>{setDark(x=>{localStorage.setItem('nexora-theme',!x?'dark':'light');return !x})};return <><header><Link className="brand" to="/">NEXORA <small>News, tuned to what matters.</small></Link><nav><NavLink to="/">Home</NavLink><NavLink to="/discover">Discover</NavLink><NavLink to="/trending">Trending</NavLink>{token&&<NavLink to="/recommendations">For You</NavLink>}</nav><div className="head-actions"><button className="icon" aria-label="Toggle color theme" onClick={toggle}>{dark?'☀':'◐'}</button>{token?<><Link className="profile-link" to="/profile">{profile?.name?.split(' ')[0]||'Profile'}</Link><button className="link-btn" onClick={()=>{logout();nav('/')}}>Log out</button></>:<Link className="button slim" to="/login">Sign in</Link>}</div></header><main>{children}</main><nav className="mobile-nav"><NavLink to="/">Home</NavLink><NavLink to="/discover">Discover</NavLink><NavLink to="/trending">Trending</NavLink><NavLink to={token?'/recommendations':'/login'}>{token?'For You':'Sign in'}</NavLink></nav><footer>© {new Date().getFullYear()} Nexora <span>·</span> News, tuned to what matters.</footer></>}
function Skeleton({n=4}){return <div className="grid">{Array.from({length:n},(_,i)=><div className="skeleton" key={i}/>)}</div>}
function ErrorState({message,retry}){return <section className="state"><h2>We couldn’t load this right now.</h2><p>{message}</p><button className="button" onClick={retry}>Try again</button></section>}
function Empty({title,copy,to='/discover',cta='Explore stories'}){return <section className="state"><h2>{title}</h2><p>{copy}</p><Link className="button" to={to}>{cta}</Link></section>}
function NewsCard({item,featured=false,reason,rank,actions=false,onBookmark}){const id=item._id||item.id;return <article className={'news-card '+(featured?'featured':'')}><Link to={`/article/${id}`} className="card-image">{item.image_url?<img src={item.image_url} loading="lazy" alt=""/>:<span>N</span>}</Link><div className="card-body">{rank&&<b className="rank">{String(rank).padStart(2,'0')}</b>}<div className="eyebrow">{item.category||'News'} <i/> {item.source||'Nexora'}</div><h2><Link to={`/article/${id}`}>{item.title||'Untitled story'}</Link></h2><p>{excerpt(item.content)}</p><div className="meta">{fmt(item.created_at||item.published)} {reason&&<em>{reason}</em>}</div>{actions&&<button className="link-btn save" onClick={()=>onBookmark?.(id)}>Save story</button>}</div></article>}
function Home(){const {token,profile}=useAuth();const news=useFetch(()=>api.get('/news',{params:{page:1,limit:9}}).then(r=>r.data),[]);const trend=useFetch(()=>api.get('/trending').then(r=>r.data),[]);const rec=useFetch(()=>token?api.get('/personalized-recommendations').then(r=>r.data):Promise.resolve(null),[token]);if(news.loading)return <Shell><Hero/><Skeleton n={6}/></Shell>;if(news.error)return <Shell><ErrorState {...news}/></Shell>;const items=news.data?.news||[];const recommendations=rec.data?.recommendations||[];return <Shell><Hero profile={profile} count={recommendations.length}/><section className="lead">{items[0]?<NewsCard item={items[0]} featured/>:<Empty title="No stories yet." copy="News will appear here when the backend has content."/>}</section>{token&&recommendations.length>0&&<Section title="For you" intro={rec.data?.recommendations?.[0]?.reason?.includes('trending')?'Start reading. Nexora will learn what matters to you.':'Selected from the topics you’re exploring.'}><div className="grid">{recommendations.slice(0,3).map(x=><NewsCard key={x._id} item={x} reason={humanReason(x.reason)}/>)}</div><Link className="text-link" to="/recommendations">See all recommendations →</Link></Section>}<Section title="Latest intelligence" intro="A live view of the newest stories in your news stream."><div className="grid">{items.slice(1,7).map(x=><NewsCard key={x._id} item={x}/>)}</div><Link className="text-link" to="/discover">Explore all stories →</Link></Section>{trend.data?.trending_news?.length>0&&<Section title="Trending now" intro="Global momentum across Nexora — not personalized."><div className="compact-list">{trend.data.trending_news.slice(0,4).map((x,i)=><NewsCard key={x._id} item={x} rank={i+1}/>)}</div></Section>}</Shell>}
function Hero({profile,count}){return <section className="hero"><div><span className="kicker">PERSONAL INTELLIGENCE / LIVE</span><h1>{profile?`Good ${new Date().getHours()<12?'morning':'afternoon'}, ${profile.name?.split(' ')[0]||'there'}.`:'Understand the day in context.'}</h1><p>{count?`Your reading signal is shaping ${count} fresh recommendations.`:'Current stories, global momentum, and a smarter reading habit.'}</p></div><div className="hero-mark">N<span>×</span></div></section>}
function Section({title,intro,children}){return <section className="section"><div className="section-heading"><div><h1>{title}</h1>{intro&&<p>{intro}</p>}</div></div>{children}</section>}
function humanReason(r){if(!r)return 'Picked for you';if(r.toLowerCase().includes('trending'))return 'Trending among readers';return r.replace(/Recommended because/i,'Because').replace(/semantic|score/gi,'').trim()}
function Discover(){const [params,setParams]=useSearchParams();const q=params.get('q')||'';const [value,setValue]=useState(q);const result=useFetch(()=>q?api.get('/news/search',{params:{q}}).then(r=>r.data):api.get('/news',{params:{page:1,limit:24}}).then(r=>r.data),[q]);const list=result.data?.news||result.data?.results||[];return <Shell><PageTitle eyebrow="DISCOVER" title="Find the signal." copy="Search the latest stories by topic, author, or category."/><form className="search" onSubmit={e=>{e.preventDefault();setParams(value.trim()?{q:value.trim()}:{})}}><input aria-label="Search news" placeholder="Search news, topics, or authors" value={value} onChange={e=>setValue(e.target.value)}/><button className="button">Search</button></form>{result.loading?<Skeleton n={8}/>:result.error?<ErrorState {...result}/>:list.length?<div className="grid">{list.map(x=><NewsCard key={x._id} item={x}/>)}</div>:<Empty title="No stories found." copy="Try another topic or a broader search phrase."/>}</Shell>}
function Trending(){const res=useFetch(()=>api.get('/trending').then(r=>r.data),[]);return <Shell><PageTitle eyebrow="GLOBAL PULSE" title="Trending now." copy="Stories gaining attention across all Nexora readers."/>{res.loading?<Skeleton/>:res.error?<ErrorState {...res}/>:res.data?.trending_news?.length?<div className="trend-list">{res.data.trending_news.map((x,i)=><NewsCard key={x._id} item={x} rank={i+1} reason={`${x.likes||0} likes · ${x.bookmarks||0} saves`}/>)}</div>:<Empty title="No global trend yet." copy="Trending stories will emerge as readers engage with news."/>}</Shell>}
function Recommendations(){const res=useFetch(()=>api.get('/personalized-recommendations').then(r=>r.data),[]);return <Shell><PageTitle eyebrow="YOUR NEWS SIGNAL" title="Chosen for your attention." copy="Recommendations update as your reading activity evolves."/>{res.loading?<Skeleton/>:res.error?<ErrorState {...res}/>:res.data?.recommendations?.length?<div className="grid">{res.data.recommendations.map(x=><NewsCard key={x._id} item={x} reason={humanReason(x.reason)}/>)}</div>:<Empty title="Your signal is just getting started." copy="Read a few stories and Nexora will start learning your interests."/>}</Shell>}
function Article(){const {id}=useParams();const {token}=useAuth();const res=useFetch(()=>api.get(`/news/${id}`).then(r=>r.data),[id]);const [notice,setNotice]=useState('');const [busy,setBusy]=useState('');useEffect(()=>{if(token)api.post(`/reading-history/${id}`).catch(()=>{})},[id,token]);const action=async(kind)=>{if(!token){setNotice('Sign in to save and react to stories.');return}setBusy(kind);try{if(kind==='bookmark')await api.post(`/bookmark/${id}`);else await api.post(`/news/${id}/${kind}`);setNotice(kind==='bookmark'?'Saved to your reading list.':kind==='like'?'Thanks for the signal.':'We’ll show less of this kind of story.')}catch(e){setNotice(messageFor(e))}finally{setBusy('')}};if(res.loading)return <Shell><div className="article-skeleton"/></Shell>;if(res.error)return <Shell><ErrorState {...res}/></Shell>;const n=res.data?.news;if(!n)return <Shell><Empty title="This story could not be found." copy="It may have been removed from the news stream."/></Shell>;return <Shell><div className="progress"/><article className="article"><div className="eyebrow">{n.category||'News'} <i/> {n.source||'Nexora'}</div><h1>{n.title}</h1><p className="dek">{excerpt(n.content)}</p><div className="byline">{n.author&&<>By {n.author} · </>}{fmt(n.published||n.created_at)}</div><div className="story-actions"><button disabled={!!busy} onClick={()=>action('like')}>♡ Like</button><button disabled={!!busy} onClick={()=>action('dislike')}>⊘ Not for me</button><button disabled={!!busy} onClick={()=>action('bookmark')}>⌑ Save</button></div>{n.image_url&&<img className="article-image" src={n.image_url} alt=""/>}<div className="article-body">{text(n.content).split(/\n+/).filter(Boolean).map((p,i)=><p key={i}>{p}</p>)}</div></article><Toast notice={notice}/></Shell>}
function Bookmarks(){const res=useFetch(()=>api.get('/bookmarks').then(r=>r.data),[]);const [notice,setNotice]=useState('');const remove=async id=>{try{await api.delete(`/bookmark/${id}`);setNotice('Removed from your reading list.');res.reload()}catch(e){setNotice(messageFor(e))}};return <Shell><PageTitle eyebrow="PERSONAL LIBRARY" title="Saved for later." copy="Keep the stories you want to return to."/>{res.loading?<Skeleton/>:res.error?<ErrorState {...res}/>:res.data?.bookmarks?.length?<><div className="grid">{res.data.bookmarks.map(x=><NewsCard key={x._id} item={x} actions onBookmark={remove}/>)}</div><Toast notice={notice}/></>:<Empty title="Your reading list is empty." copy="Save important stories and they’ll wait here."/>}</Shell>}
function Analytics(){const res=useFetch(()=>api.get('/analytics').then(r=>r.data),[]);const a=res.data?.analytics;return <Shell><PageTitle eyebrow="YOUR READING SIGNATURE" title="How you engage with the news." copy="A private summary generated from your real Nexora activity."/>{res.loading?<Skeleton n={6}/>:res.error?<ErrorState {...res}/>:a?<div className="stats">{[['Articles read',a.total_articles_read],['Bookmarks',a.total_bookmarks],['Likes',a.total_likes],['Dislikes',a.total_dislikes],['Favorite category',a.favorite_category],['Favorite author',a.favorite_author]].map(([k,v])=><div className="stat" key={k}><span>{k}</span><strong>{v??'—'}</strong></div>)}</div>:<Empty title="Your signature is still forming." copy="Read a few stories to see your activity."/>}</Shell>}
function Profile(){const {profile,user,logout}=useAuth();const nav=useNavigate();return <Shell><PageTitle eyebrow="ACCOUNT" title="Your Nexora." copy="Your profile and personal reading space."/><section className="profile-panel"><div className="avatar">{(profile?.name||'N').slice(0,1)}</div><h2>{profile?.name||'Loading profile…'}</h2><p>{profile?.email}</p><p className="role">{user?.role||'user'}</p><div className="profile-links"><Link to="/bookmarks">Bookmarks</Link><Link to="/analytics">Reading signature</Link><Link to="/recommendations">Recommendations</Link>{user?.role==='admin'&&<Link to="/admin">Admin dashboard</Link>}<button onClick={()=>{logout();nav('/')}}>Log out</button></div><p className="muted">Reading-history browsing is unavailable because the current backend exposes no history retrieval endpoint.</p></section></Shell>}
function Admin(){const res=useFetch(()=>api.get('/admin/dashboard').then(r=>r.data),[]);const d=res.data?.dashboard;return <Shell><PageTitle eyebrow="OPERATIONS" title="Admin dashboard." copy="Current system activity from the live backend."/>{res.loading?<Skeleton n={6}/>:res.error?<ErrorState {...res}/>:d?<div className="stats admin-stats">{Object.entries(d).map(([k,v])=><div className="stat" key={k}><span>{k.replaceAll('_',' ')}</span><strong>{v}</strong></div>)}</div>:null}</Shell>}
function PageTitle({eyebrow,title,copy}){return <section className="page-title"><span className="kicker">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></section>}
function Login({register=false}){const {login}=useAuth();const nav=useNavigate();const [form,setForm]=useState({name:'',email:'',password:'',confirm:''});const [error,setError]=useState('');const [busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setError('');if(register&&form.password!==form.confirm)return setError('Passwords do not match.');setBusy(true);try{if(register){await api.post('/register',{name:form.name,email:form.email,password:form.password});nav('/login',{state:{registered:true}})}else{const r=await api.post('/login',{email:form.email,password:form.password});login(r.data.token);nav('/')}}catch(e){setError(e?.response?.data?.message||messageFor(e))}finally{setBusy(false)}};return <div className="auth"><Link className="brand" to="/">NEXORA <small>News, tuned to what matters.</small></Link><form className="auth-form" onSubmit={submit}><span className="kicker">{register?'BEGIN YOUR READING SIGNAL':'WELCOME BACK'}</span><h1>{register?'Make news more personal.':'Sign in to Nexora.'}</h1>{register&&<label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required minLength="8" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{register&&<label>Confirm password<input required type="password" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/></label>}{error&&<p className="form-error" role="alert">{error}</p>}<button disabled={busy} className="button">{busy?'Please wait…':register?'Create account':'Sign in'}</button><p>{register?'Already have an account?':'New to Nexora?'} <Link to={register?'/login':'/register'}>{register?'Sign in':'Create an account'}</Link></p></form></div>}
function Private({children,admin=false}){const {token,user}=useAuth();if(!token)return <Navigate to="/login" replace/>;if(admin&&user?.role!=='admin')return <Shell><ErrorState message="You don't have permission to access this page." retry={()=>history.back()}/></Shell>;return children}
function App(){return <AuthProvider><Routes><Route path="/" element={<Home/>}/><Route path="/discover" element={<Discover/>}/><Route path="/trending" element={<Trending/>}/><Route path="/article/:id" element={<Article/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Login register/>}/><Route path="/recommendations" element={<Private><Recommendations/></Private>}/><Route path="/bookmarks" element={<Private><Bookmarks/></Private>}/><Route path="/analytics" element={<Private><Analytics/></Private>}/><Route path="/profile" element={<Private><Profile/></Private>}/><Route path="/admin" element={<Private admin><Admin/></Private>}/><Route path="*" element={<Shell><Empty title="Page not found." copy="That route doesn’t exist in Nexora."/></Shell>}/></Routes></AuthProvider>};createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
